/** Vitality & Grace 设计令牌（来自设计稿 DESIGN.md） */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#9b4430',
        'primary-container': '#e67e66',
        'on-primary': '#ffffff',
        'on-primary-container': '#611909',
        'primary-fixed': '#ffdad2',
        'primary-fixed-dim': '#ffb4a3',
        'inverse-primary': '#ffb4a3',
        secondary: '#735c00',
        'secondary-container': '#fed65b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#745c00',
        'secondary-fixed': '#ffe088',
        tertiary: '#645e49',
        'tertiary-container': '#a29b83',
        surface: '#fcf9f8',
        'surface-bright': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e4e2e1',
        'surface-variant': '#e4e2e1',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#55423e',
        outline: '#88726d',
        'outline-variant': '#dbc1bb',
        background: '#fcf9f8',
        'on-background': '#1b1c1c',
        error: '#ba1a1a',
        mint: '#E0F2F1',
        lavender: '#F3E5F5',
      },
      borderRadius: { DEFAULT: '1rem', lg: '2rem', xl: '3rem', full: '9999px' },
      spacing: {
        unit: '8px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '16px',
        'section-gap': '64px',
        'container-padding-mobile': '24px',
        'container-padding-desktop': '64px',
      },
      fontFamily: {
        headline: ['Be Vietnam Pro', 'sans-serif'],
        display: ['Be Vietnam Pro', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
