// Slique 斯俪 — Training Data Library
// Evidence-based posture courses and structured programs
// Brand language: 舒展 归位 唤醒 复位 立 松弛 轻盈 生长 秩序 重塑 焕新 安放 从容

const courses = [
  // ─────────────────────────────────────────────────────────────────────────
  // C1  颈线 · 养成  (neck, 初级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c1',
    name: '颈线 · 养成',
    desc: '颈线向上 · 轻盈生长',
    category: 'neck',
    duration: 15,
    level: '初级',
    icon: 'self_improvement',
    bg: '1',
    evidence: 'A',
    scenes: ['home','office'],
    targetMuscles: {
      activate: ['深颈屈肌', '菱形肌'],
      release: ['上斜方肌', '胸锁乳突肌'],
    },
    moves: [
      {
        id: 'c1-m1',
        name: '颈侧 · 舒展',
        duration: 45,
        sets: 2,
        reps: '45秒 / 侧',
        desc: '坐立或站立，右耳缓缓向右肩靠近，左手轻压头顶辅助加深。保持颈侧长度，自然呼吸。左右交替。',
        tip: '肩膀放松下沉，不要耸肩',
        icon: 'self_improvement',
        phase: 'release',
      },
      {
        id: 'c1-m2',
        name: '枕下 · 松弛',
        duration: 60,
        sets: 1,
        reps: '60秒',
        desc: '仰卧，双手指尖轻轻置于颅骨底部（枕骨下方），感受颈后根部的温热与松弛。头部重量由双手托住。',
        tip: '闭眼，专注感受颈后的释放',
        icon: 'spa',
        phase: 'release',
      },
      {
        id: 'c1-m3',
        name: '颈线 · 内收',
        duration: 30,
        sets: 3,
        reps: '10次 / 保持10秒',
        desc: '仰卧屈膝，下颌缓慢向喉咙方向内收，颈后轻轻拉长贴近垫面。保持10秒后放松，重复10次。不要低头，只做平行内收。',
        tip: '想象头顶被轻轻向后上方牵引，颈后变长',
        icon: 'self_improvement',
        phase: 'activate',
      },
      {
        id: 'c1-m4',
        name: '颈肩 YTW · 俯卧',
        duration: 30,
        sets: 2,
        reps: '各字母 10次 / 保持5秒',
        desc: '俯卧，额头轻放于折叠毛巾上。依次做Y（双臂斜上举）、T（双臂侧平举）、W（肘弯曲外旋至耳侧）三个姿势，每个姿势保持5秒。肩胛骨向脊柱中间归位。',
        tip: '动作由肩胛骨发力，而非手臂；腰部不要过度用力',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c1-m5',
        name: '靠墙站立 · 体态整合',
        duration: 60,
        sets: 3,
        reps: '60秒',
        desc: '后脑、肩胛骨、臀部、脚跟四点靠墙站立。下颌内收，颈线向上延伸。感受脊柱的自然曲线，均匀呼吸。',
        tip: '腰部与墙面保留一掌宽的自然间隙，不要刻意压平',
        icon: 'accessibility_new',
        phase: 'integrate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C2  颈背 · 唤醒  (neck, 中级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c2',
    name: '颈背 · 唤醒',
    desc: '深层唤醒 · 重建颈背秩序',
    category: 'neck',
    duration: 20,
    level: '中级',
    icon: 'self_improvement',
    bg: '1',
    evidence: 'A',
    scenes: ['home','office'],
    targetMuscles: {
      activate: ['深颈屈肌', '中下斜方肌', '菱形肌'],
      release: ['上斜方肌', '肩胛提肌', '胸小肌'],
    },
    moves: [
      {
        id: 'c2-m1',
        name: '上斜方肌 · 泡沫轴松弛',
        duration: 60,
        sets: 1,
        reps: '60秒 / 侧',
        desc: '侧卧，泡沫轴置于颈肩交界处，缓慢上下滚动，在紧绷处停留10-15秒。左右各60秒。',
        tip: '呼气时有意识放松肩颈，不要闭气',
        icon: 'sports_gymnastics',
        phase: 'release',
      },
      {
        id: 'c2-m2',
        name: '胸椎 · 旋转舒展',
        duration: 40,
        sets: 2,
        reps: '10次 / 侧',
        desc: '四足跪姿，一手置于头后，以胸椎为轴向上旋转打开，眼睛跟随手肘方向。腰椎保持稳定，只旋转上背。左右交替。',
        tip: '旋转来自胸椎，腰部不要跟着扭转',
        icon: 'rotate_right',
        phase: 'release',
      },
      {
        id: 'c2-m3',
        name: '颈线内收 · 进阶',
        duration: 30,
        sets: 3,
        reps: '10次 / 保持10秒',
        desc: '坐于椅边，脊柱自然直立，下颌缓慢内收、颈后延伸，保持10秒。可在颈后与墙之间夹一个小气球辅助感知。',
        tip: '收下颌时保持眼神水平，不要歪头',
        icon: 'self_improvement',
        phase: 'activate',
      },
      {
        id: 'c2-m4',
        name: '弹力带 · 面拉',
        duration: 30,
        sets: 3,
        reps: '12次 / 保持2秒',
        desc: '弹力带固定于眼睛高度，双手握带向面部拉，肘部外展与肩齐平，拇指指向耳后，末端停留2秒感受肩胛骨归位。',
        tip: '拉至终点时肩胛骨向中间夹紧，不要耸肩',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c2-m5',
        name: '俯卧 YTW · 完整版',
        duration: 30,
        sets: 3,
        reps: '各字母 10次',
        desc: '俯卧，胸部轻微抬离地面。Y字（斜上方）、T字（正侧方）、W字（肘弯外旋）各10次，全程感受肩胛骨下沉内收。',
        tip: '控制慢起慢落，每次2秒上 2秒下',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c2-m6',
        name: '肩胛稳定 · 整合',
        duration: 45,
        sets: 3,
        reps: '45秒',
        desc: '靠墙站立，双臂举至W字位，沿墙面缓慢上滑至Y字位，再缓慢回落。全程后脑、肩胛、臀部贴墙，动作范围内不脱离墙面。',
        tip: '感受每一次上滑时颈线的延伸与肩膀的下沉',
        icon: 'accessibility_new',
        phase: 'integrate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C3  舒展  (shoulder, 初级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c3',
    name: '肩背 · 舒展',
    desc: '打开前侧 · 让肩膀归位',
    category: 'shoulder',
    duration: 20,
    level: '初级',
    icon: 'accessibility_new',
    bg: '2',
    evidence: 'A',
    scenes: ['home','office'],
    targetMuscles: {
      activate: ['中下斜方肌', '菱形肌', '冈下肌'],
      release: ['胸大肌', '胸小肌', '前锯肌紧张部'],
    },
    moves: [
      {
        id: 'c3-m1',
        name: '胸肌门框拉伸 · 高位',
        duration: 45,
        sets: 2,
        reps: '45秒 × 2组',
        desc: '面对门框站立，双臂举过头顶呈120°扶门框，身体缓慢前倾，感受锁骨下方胸肌上部的拉伸。保持45秒。',
        tip: '下背保持稳定，不要过度弓腰',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c3-m2',
        name: '胸肌门框拉伸 · 低位',
        duration: 45,
        sets: 2,
        reps: '45秒 × 2组',
        desc: '面对门框，双臂平举（90°）扶门框，身体前倾，感受胸肌中部与前肩的拉伸。保持45秒。',
        tip: '双肩下沉，不要让肩膀跑向耳朵',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c3-m3',
        name: '墙天使',
        duration: 30,
        sets: 3,
        reps: '12次',
        desc: '背贴墙站立，双臂弯曲成W字贴墙，缓慢沿墙上滑至Y字，再沿墙落回W字。全程手背、肘部、后脑不离墙。',
        tip: '感受肩胛骨随动作下沉和上旋，腰与墙保留自然间隙',
        icon: 'self_improvement',
        phase: 'activate',
      },
      {
        id: 'c3-m4',
        name: '俯卧 YTW-T · 激活',
        duration: 30,
        sets: 3,
        reps: '10次 / 保持5秒',
        desc: '俯卧，着重做T字（双臂侧平举）姿势，拇指朝上，肩胛骨向中间归位，保持5秒。感受中斜方肌和菱形肌的收缩。',
        tip: '头部自然延伸，不要仰头；控制腰部不要过度塌',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c3-m5',
        name: '侧卧外旋 · 激活',
        duration: 30,
        sets: 3,
        reps: '12次 / 保持2秒',
        desc: '侧卧，上方手臂肘部弯曲90°贴于体侧，以肘为轴向上外旋至与地面平行，保持2秒后慢慢落回。激活冈下肌与小圆肌。',
        tip: '肘部始终贴住腰侧，只做外旋动作',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c3-m6',
        name: '胸椎泡沫轴 · 伸展',
        duration: 60,
        sets: 1,
        reps: '60秒',
        desc: '泡沫轴横置于上背（肩胛骨下角附近），双手抱头，缓慢向后伸展，在每节胸椎处停留5-10秒后移动到下一节。',
        tip: '腰部不要压在泡沫轴上；呼气时让胸椎放松下沉',
        icon: 'sports_gymnastics',
        phase: 'release',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C4  肩背 · 打开  (shoulder, 中级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c4',
    name: '肩背 · 打开',
    desc: '肩胛重塑 · 背部从容展开',
    category: 'shoulder',
    duration: 25,
    level: '中级',
    icon: 'fitness_center',
    bg: '2',
    evidence: 'A',
    scenes: ['home','office'],
    targetMuscles: {
      activate: ['中下斜方肌', '菱形肌', '前锯肌', '冈下肌'],
      release: ['胸小肌', '上斜方肌'],
    },
    moves: [
      {
        id: 'c4-m1',
        name: '胸椎旋转 · 热身',
        duration: 40,
        sets: 2,
        reps: '10次 / 侧',
        desc: '四足跪姿，一手置于头后，胸椎向上旋转，眼睛和肘部朝向天花板。控制速度，每侧10次后换边。',
        tip: '腰部保持中立，旋转动作来自胸椎',
        icon: 'rotate_right',
        phase: 'release',
      },
      {
        id: 'c4-m2',
        name: '开胸拉伸',
        duration: 60,
        sets: 1,
        reps: '60秒',
        desc: '跪于瑜伽垫边，一手臂伸直置于地面向侧滑，胸口顺势向下向侧打开，停留60秒感受腋下与胸前的深层拉伸。',
        tip: '臀部保持在膝盖正上方，不要侧移',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c4-m3',
        name: '弹力带面拉 · 强化',
        duration: 30,
        sets: 3,
        reps: '15次',
        desc: '弹力带固定于眼高，双手握带向面部拉，肘部外展，末端停留1秒感受肩胛骨用力归位。3组15次，组间休息45秒。',
        tip: '不要用上斜方肌代偿；肩胛骨的归位感是关键',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c4-m4',
        name: '俯卧完整 YTW',
        duration: 30,
        sets: 3,
        reps: '各字母 10次',
        desc: 'Y（斜上45°）、T（侧平举90°）、W（肘弯外旋）各10次为一组，全程感受中下斜方肌与菱形肌发力，拇指朝上。',
        tip: '量力而行，有困难可俯身于椅面上完成',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c4-m5',
        name: '弹力带斜向屈曲 · 低到高',
        duration: 30,
        sets: 3,
        reps: '12次',
        desc: '弹力带固定于低处，单手握带从斜下方对角拉向对侧高处，全程手臂伸直，感受前锯肌和中斜方肌协同发力。',
        tip: '躯干不要随动作旋转，保持稳定',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c4-m6',
        name: '俯身哑铃划船',
        duration: 30,
        sets: 3,
        reps: '10次',
        desc: '双脚与肩同宽，俯身约45°，哑铃垂于身前。以肘带动，将哑铃向髋部方向上拉，顶点停留1秒夹紧肩胛骨，慢慢下放。',
        tip: '背部保持平直；是划船而不是耸肩',
        icon: 'fitness_center',
        phase: 'integrate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C5  骨盆 · 归位  (pelvis, 初级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c5',
    name: '骨盆 · 归位',
    desc: '骨盆归位 · 重心回到中央',
    category: 'pelvis',
    duration: 18,
    level: '初级',
    icon: 'accessibility_new',
    bg: '3',
    evidence: 'A',
    scenes: ['home','gym'],
    targetMuscles: {
      activate: ['臀大肌', '臀中肌', '腹横肌'],
      release: ['髂腰肌', '股直肌', '阔筋膜张肌'],
    },
    moves: [
      {
        id: 'c5-m1',
        name: '髋屈肌 · 半跪拉伸',
        duration: 60,
        sets: 2,
        reps: '60秒 / 侧',
        desc: '半跪姿（后膝跪地），前腿弓步，骨盆后倾（轻收尾骨），身体直立向前移重心，感受后腿髋前方的拉伸。保持60秒，换边。',
        tip: '骨盆后倾是关键——收尾骨才能真正拉伸到髂腰肌',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c5-m2',
        name: '股直肌 · 沙发拉伸',
        duration: 45,
        sets: 2,
        reps: '45秒 / 侧',
        desc: '半跪于垫面，后脚背靠在椅子或沙发上，骨盆保持后倾，感受大腿前侧深层的拉伸。45秒后换边。',
        tip: '腰部不要过度前弓；收腹收尾骨维持骨盆后倾',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c5-m3',
        name: '骨盆后倾 · 意识建立',
        duration: 30,
        sets: 3,
        reps: '15次 / 保持5秒',
        desc: '仰卧屈膝，缓慢将腰部贴向垫面（骨盆后倾），感受腹部轻微收紧，保持5秒后放松。建立骨盆中立意识。',
        tip: '动作幅度小而精准，不是用力压腰，而是轻轻归位',
        icon: 'self_improvement',
        phase: 'activate',
      },
      {
        id: 'c5-m4',
        name: '臀桥',
        duration: 30,
        sets: 3,
        reps: '15次 / 保持2秒',
        desc: '仰卧屈膝，脚跟与臀同宽，脚踩实地面。收腹，以臀部发力将骨盆推向天花板，顶端保持2秒，感受臀部充分收缩，缓慢下落。',
        tip: '顶端不要过度挺腰；是臀部用力而非腰部撑起',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c5-m5',
        name: '鸟狗式',
        duration: 30,
        sets: 3,
        reps: '10次 / 侧 / 保持5秒',
        desc: '四足跪姿，脊柱中立。同时伸出对侧手臂与腿，保持5秒，感受背部肌肉对称发力与核心稳定。缓慢回位，换边。',
        tip: '伸展时腰部不要旋转或塌陷；想象背上放一杯水',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c5-m6',
        name: '蚌式 · 弹力带',
        duration: 30,
        sets: 3,
        reps: '15次 / 侧',
        desc: '弹力带套于膝盖上方，侧卧屈膝，脚跟并拢，上方膝盖缓慢向上打开如蚌壳，顶端停留1秒后慢慢落回。激活臀中肌。',
        tip: '骨盆不要随膝盖一起后倒；只动膝盖，不动骨盆',
        icon: 'fitness_center',
        phase: 'activate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C6  核心 · 立  (pelvis, 中级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c6',
    name: '核心 · 立',
    desc: '核心归位 · 由内而外地立起来',
    category: 'pelvis',
    duration: 25,
    level: '中级',
    icon: 'fitness_center',
    bg: '3',
    evidence: 'A',
    scenes: ['home','gym'],
    targetMuscles: {
      activate: ['腹横肌', '臀大肌', '臀中肌', '多裂肌'],
      release: ['阔筋膜张肌', '髂腰肌'],
    },
    moves: [
      {
        id: 'c6-m1',
        name: '阔筋膜张肌 · 泡沫轴松弛',
        duration: 45,
        sets: 2,
        reps: '45秒 / 侧',
        desc: '侧卧，泡沫轴置于大腿外侧（从髋部到膝盖），缓慢滚动，在紧绷处停留10秒。注意区分大腿外侧与髂胫束。',
        tip: '找到酸胀点后保持停留，不要快速来回滚动',
        icon: 'sports_gymnastics',
        phase: 'release',
      },
      {
        id: 'c6-m2',
        name: '弓步髋屈肌 · 深度拉伸',
        duration: 60,
        sets: 2,
        reps: '60秒 / 侧',
        desc: '半跪弓步，后腿膝盖着地，骨盆后倾，前腿弓步，可将同侧手臂向上举起加深拉伸，感受髂腰肌的深度舒展。',
        tip: '呼气时有意识放松髋前，让拉伸自然加深',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c6-m3',
        name: '死虫式 · 腹横肌激活',
        duration: 30,
        sets: 3,
        reps: '8次 / 侧',
        desc: '仰卧，双臂指向天花板，双腿抬起屈膝90°。呼气收腹（感受腰背贴近垫面），缓慢将对侧手臂和腿同时向外延伸，接近地面但不触地，吸气回位。',
        tip: '腰部始终不能抬离垫面；这是核心控制而非力量练习',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c6-m4',
        name: '单腿臀桥',
        duration: 30,
        sets: 3,
        reps: '10次 / 侧',
        desc: '仰卧，一腿屈膝踩地，另一腿抬起伸直。用单腿蹬地将骨盆推起，保持骨盆水平，顶端2秒，缓慢下落。',
        tip: '非支撑侧骨盆不要下沉；感受支撑侧臀部充分用力',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c6-m5',
        name: '蚌式进阶 · 弹力带',
        duration: 30,
        sets: 3,
        reps: '15次 / 侧',
        desc: '弹力带套于膝上，侧卧，上方腿在做蚌式打开的同时向上轻微抬起（同时外展+外旋），增加臀中肌的挑战。',
        tip: '骨盆保持稳定；动作控制比幅度更重要',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c6-m6',
        name: '高脚杯深蹲',
        duration: 30,
        sets: 3,
        reps: '10次',
        desc: '双手捧持哑铃或壶铃于胸前，双脚略宽于肩，脚尖微外展。保持胸椎直立，骨盆中立，缓慢下蹲至大腿与地面平行，臀部发力蹬起。',
        tip: '下蹲时膝盖跟随脚尖方向，不要内扣；感受臀部和大腿均匀用力',
        icon: 'fitness_center',
        phase: 'integrate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C7  腰背 · 安放  (back, 初级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c7',
    name: '腰背 · 安放',
    desc: '腰背安放 · 找到脊柱的从容',
    category: 'back',
    duration: 20,
    level: '初级',
    icon: 'spa',
    bg: '4',
    evidence: 'A',
    scenes: ['home'],
    targetMuscles: {
      activate: ['腹横肌', '多裂肌', '臀大肌'],
      release: ['竖脊肌', '腰方肌'],
    },
    moves: [
      {
        id: 'c7-m1',
        name: '猫牛式 · 脊柱律动',
        duration: 60,
        sets: 1,
        reps: '10次缓慢',
        desc: '四足跪姿，吸气时胸口向下、尾骨上翘（牛式），呼气时背部拱起、尾骨内收（猫式）。随呼吸节奏缓慢完成10次，找到脊柱的流动感。',
        tip: '速度要慢，感受每一节脊椎的律动；不要只做颈部和腰部',
        icon: 'self_improvement',
        phase: 'release',
      },
      {
        id: 'c7-m2',
        name: 'DNS 90/90 · 腹式呼吸',
        duration: 180,
        sets: 1,
        reps: '3-5分钟',
        desc: '仰卧，双腿搭放在椅子或沙发上（髋和膝均约90°），腰背完全放松贴地。双手放于肋骨两侧，吸气时感受肋骨向四面八方扩张（360°呼吸），呼气时自然回落。',
        tip: '这是放松练习，不要用力；让腰背因重力自然安放在垫面',
        icon: 'spa',
        phase: 'release',
      },
      {
        id: 'c7-m3',
        name: '腹横肌激活 · Draw-in',
        duration: 30,
        sets: 3,
        reps: '10次 / 保持10秒',
        desc: '仰卧屈膝，正常呼吸后呼气末端轻轻将肚脐内收向脊柱（不是用力收腹，而是轻柔内收），保持10秒，继续正常呼吸，不要憋气。',
        tip: '力度约20%——是轻柔激活，不是用力吸腹',
        icon: 'self_improvement',
        phase: 'activate',
      },
      {
        id: 'c7-m4',
        name: '臀桥 · 腰背稳定',
        duration: 30,
        sets: 3,
        reps: '15次',
        desc: '仰卧屈膝，先做腹横肌激活，再以臀部发力将骨盆推起。感受腰背在运动中保持稳定，臀部主导发力。',
        tip: '每次推起前先激活腹横肌，建立"先稳定再运动"的习惯',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c7-m5',
        name: '死虫式 · 初级',
        duration: 30,
        sets: 3,
        reps: '8次 / 侧',
        desc: '仰卧，双臂指向天花板，屈膝抬腿90°。收腹后，缓慢将单侧腿向前下方伸展（脚跟接近地面），对侧手臂向头顶延伸，腰部不离垫面。',
        tip: '腰部的稳定比腿的高度更重要；腿不需要放得很低',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c7-m6',
        name: '平板支撑 · 骨盆后倾',
        duration: 30,
        sets: 3,
        reps: '30秒',
        desc: '肘支平板，主动将骨盆轻微后倾（收尾骨），感受腹部深层收紧，背部保持一条直线。保持30秒，均匀呼吸。',
        tip: '是骨盆的主动后倾，不是塌腰，也不是撅臀；找到中立稳定位',
        icon: 'fitness_center',
        phase: 'integrate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C8  腰背 · 深层唤醒  (back, 中级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c8',
    name: '腰背 · 深层唤醒',
    desc: '深层唤醒 · 脊柱稳定的重塑',
    category: 'back',
    duration: 25,
    level: '中级',
    icon: 'fitness_center',
    bg: '4',
    evidence: 'A',
    scenes: ['home'],
    targetMuscles: {
      activate: ['多裂肌', '腹横肌', '臀大肌', '腘绳肌'],
      release: ['竖脊肌', '腰方肌'],
    },
    moves: [
      {
        id: 'c8-m1',
        name: '竖脊肌 · 泡沫轴松弛',
        duration: 60,
        sets: 1,
        reps: '60秒',
        desc: '仰卧，泡沫轴横置于中背，双手托头，缓慢上下滚动覆盖整个背部（胸椎为主，避免直接压在腰椎上）。在紧绷处停留。',
        tip: '腰部感到不适时立刻移开；主要放松胸椎和中背',
        icon: 'sports_gymnastics',
        phase: 'release',
      },
      {
        id: 'c8-m2',
        name: 'DNS呼吸 · 进阶版',
        duration: 300,
        sets: 1,
        reps: '5分钟',
        desc: '仰卧，双腿搭于椅上（90/90位），一手置腹部，一手置肋骨侧面。练习360°肋骨扩张呼吸，呼气时主动感受腹横肌轻柔内收，建立腹内压。',
        tip: '呼气末端保持轻柔的腹部张力，这是深层核心的基础',
        icon: 'spa',
        phase: 'release',
      },
      {
        id: 'c8-m3',
        name: '鸟狗式 · 进阶控制',
        duration: 30,
        sets: 3,
        reps: '10次 / 侧',
        desc: '四足跪姿，先激活腹横肌，再缓慢延伸对侧手脚。在终点位置保持5秒，感受腰背肌肉均衡发力。用肘划圈（高级变式）可增加挑战。',
        tip: '背部不能旋转或塌陷；控制是目的，不是速度',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c8-m4',
        name: '平板支撑 · 进阶',
        duration: 45,
        sets: 3,
        reps: '45秒',
        desc: '肘支平板，骨盆轻微后倾，腹部收紧。保持45秒，均匀呼吸，感受全身肌肉协同维持脊柱中立。',
        tip: '当无法维持脊柱中立时立刻停止，不要为了时间而代偿',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c8-m5',
        name: '单腿罗马尼亚硬拉',
        duration: 30,
        sets: 3,
        reps: '8次 / 侧',
        desc: '单腿站立，对侧腿向后延伸，上身向前俯身（铰链髋部），保持背部一条直线，感受支撑腿腘绳肌的拉伸与控制。可手持轻哑铃增加挑战。',
        tip: '运动来自髋关节铰链，不是背部弯曲；保持脊柱中立',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c8-m6',
        name: '功能性弓步 · 整合',
        duration: 30,
        sets: 3,
        reps: '8次 / 侧',
        desc: '站立，向前迈步弓步下蹲，前脚落地同时双手过头顶，感受腰背与核心在功能性动作中的稳定与从容。缓慢收回站起，换边。',
        tip: '落步时膝盖不要内扣；全程脊柱保持直立稳定',
        icon: 'fitness_center',
        phase: 'integrate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C9  膝稳 · 养成  (knee, 初级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c9',
    name: '膝稳 · 养成',
    desc: '膝关节归位 · 稳步轻行',
    category: 'knee',
    duration: 20,
    level: '初级',
    icon: 'directions_walk',
    bg: '5',
    evidence: 'A',
    scenes: ['home','gym'],
    targetMuscles: {
      activate: ['股四头肌VMO', '腘绳肌', '臀中肌'],
      release: ['腓肠肌', '比目鱼肌', '股二头肌'],
    },
    moves: [
      {
        id: 'c9-m1',
        name: '腓肠肌 · 台阶拉伸',
        duration: 45,
        sets: 2,
        reps: '45秒 / 侧',
        desc: '站于台阶边沿，单脚前半掌踩台阶，脚跟自然下沉，腿伸直，感受小腿上段（腓肠肌）的拉伸。保持45秒，换边。',
        tip: '腿保持伸直；若重心不稳可扶墙',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c9-m2',
        name: '比目鱼肌 · 膝弯拉伸',
        duration: 45,
        sets: 2,
        reps: '45秒 / 侧',
        desc: '同样站于台阶，脚跟下沉，但这次将膝盖微微弯曲，拉伸转移到小腿深层（比目鱼肌）。保持45秒，换边。',
        tip: '膝盖弯曲方向跟随脚尖，不要内扣',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c9-m3',
        name: '弹力带TKE · 终末膝关节伸展',
        duration: 30,
        sets: 3,
        reps: '15次 / 保持2秒',
        desc: '弹力带固定于低处套于膝盖后方，站立微微屈膝，对抗阻力将膝盖最后15°伸直，顶端保持2秒感受大腿内侧（VMO）收缩，慢慢弯回。',
        tip: 'TKE专门针对膝过伸或膝无力：终末段的锁定感是训练目标',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c9-m4',
        name: '臀桥 · 腘绳肌激活',
        duration: 30,
        sets: 3,
        reps: '10次',
        desc: '仰卧，脚跟尽量靠近臀部（约一掌距离），这样腘绳肌参与度更高。收腹，以臀+腘绳肌共同发力推起骨盆，顶端2秒后缓慢下落。',
        tip: '脚跟主动下压地面，感受大腿后侧的参与',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c9-m5',
        name: '单腿平衡站立',
        duration: 30,
        sets: 3,
        reps: '30秒 / 侧',
        desc: '单腿站立，保持膝盖轻微弯曲（不锁死），对侧腿悬空。感受脚踝和膝盖的本体感觉控制。挑战者可闭眼进行。',
        tip: '视线固定一点；膝盖保持与第二趾对齐，不要内扣',
        icon: 'accessibility_new',
        phase: 'activate',
      },
      {
        id: 'c9-m6',
        name: '微蹲单腿 · 稳定',
        duration: 30,
        sets: 3,
        reps: '10次 / 侧',
        desc: '单腿站立，以髋为轴缓慢下蹲至约30°（浅蹲），保持膝盖稳定，臀部控制全程。慢慢站起，重复10次后换边。',
        tip: '下蹲时膝盖不要超过脚尖太多，不要内扣；臀部发力站起',
        icon: 'fitness_center',
        phase: 'integrate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C10  膝稳 · 进阶  (knee, 中级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c10',
    name: '膝稳 · 进阶',
    desc: '强化膝周 · 动态秩序',
    category: 'knee',
    duration: 25,
    level: '中级',
    icon: 'fitness_center',
    bg: '5',
    evidence: 'A',
    scenes: ['gym'],
    targetMuscles: {
      activate: ['腘绳肌', '股四头肌', '臀大肌', '小腿三头肌'],
      release: ['股四头肌', '髂胫束'],
    },
    moves: [
      {
        id: 'c10-m1',
        name: '股四头肌 · 站立拉伸',
        duration: 30,
        sets: 2,
        reps: '30秒 / 侧',
        desc: '单腿站立，同侧手握住脚踝向臀部靠近，感受大腿前侧拉伸，骨盆保持中立（不要翘臀）。保持30秒，换边。',
        tip: '膝盖两侧保持并拢，不要外展；骨盆中立是关键',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c10-m2',
        name: '北欧腘绳肌离心弯举',
        duration: 40,
        sets: 2,
        reps: '6次 / 离心4秒',
        desc: '跪于垫上，双脚由伙伴或固定物压住。保持躯干挺直，缓慢向前倒（4秒离心），在快到地面时用手撑地控制。这是腘绳肌最强循证练习之一。',
        tip: '向前倒的过程越慢越好；这个动作难度高，量力而行',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c10-m3',
        name: '单腿罗马尼亚硬拉',
        duration: 30,
        sets: 3,
        reps: '8次 / 侧',
        desc: '单腿站立，保持脊柱中立，以髋为铰链缓慢俯身，对侧腿向后延伸平衡，感受支撑腿腘绳肌的控制。可手持哑铃增加负荷。',
        tip: '髋铰链动作，背部不弯曲；在腘绳肌有张力时停止，缓慢站起',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c10-m4',
        name: '台阶踏步 · 多方向',
        duration: 30,
        sets: 3,
        reps: '10次 / 方向',
        desc: '站于约15-20cm高台阶旁，分别向前、向侧、向后上台阶并控制下落，每个方向10次。强化膝关节在不同平面的稳定控制。',
        tip: '上台阶时膝盖跟脚尖方向，下台阶时控制慢落，不要砸落',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c10-m5',
        name: '单腿平衡盘',
        duration: 45,
        sets: 3,
        reps: '45秒 / 侧',
        desc: '单腿站于平衡盘（或折叠毛巾/枕头），保持膝盖微弯，感受踝关节和膝关节的动态稳定控制。视线固定前方。',
        tip: '重心均匀分布在脚掌三点；感受小腿肌肉的细微调整',
        icon: 'accessibility_new',
        phase: 'activate',
      },
      {
        id: 'c10-m6',
        name: '慢速深蹲 · 离心控制',
        duration: 30,
        sets: 3,
        reps: '8次 / 离心4秒',
        desc: '双脚与肩同宽，用4秒缓慢下蹲至大腿与地面平行（离心控制），在底部停留1秒后1秒站起。强调离心阶段的控制。',
        tip: '下蹲时感受股四头肌的离心张力；膝盖始终跟随脚尖方向',
        icon: 'fitness_center',
        phase: 'integrate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C11  足弓 · 生长  (foot, 初级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c11',
    name: '足弓 · 生长',
    desc: '足弓生长 · 从地面向上的秩序',
    category: 'foot',
    duration: 15,
    level: '初级',
    icon: 'directions_walk',
    bg: '6',
    evidence: 'A',
    scenes: ['home'],
    targetMuscles: {
      activate: ['足底内在肌', '胫骨后肌', '趾屈肌'],
      release: ['足底筋膜', '腓肠肌', '比目鱼肌'],
    },
    moves: [
      {
        id: 'c11-m1',
        name: '足底筋膜 · 按摩球松弛',
        duration: 60,
        sets: 1,
        reps: '60秒 / 足',
        desc: '站立，将网球或筋膜球置于足底，从脚跟向前滚动，覆盖整个足弓区域。在酸胀点停留10秒后继续移动。每足60秒。',
        tip: '体重可部分转移；不要在骨骼突起处施压',
        icon: 'sports_gymnastics',
        phase: 'release',
      },
      {
        id: 'c11-m2',
        name: '腓肠肌 · 站立拉伸',
        duration: 45,
        sets: 2,
        reps: '45秒 / 侧',
        desc: '面对墙壁，一腿向后伸直，脚跟踩实地面，前腿弓步，双手扶墙，感受后腿小腿上段的拉伸。保持45秒，换边。',
        tip: '后脚脚跟始终踩实地面，脚尖朝前',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c11-m3',
        name: '比目鱼肌 · 屈膝拉伸',
        duration: 45,
        sets: 2,
        reps: '45秒 / 侧',
        desc: '同扶墙姿势，后腿膝盖微弯，脚跟踩实地面下沉，拉伸转向小腿深层（比目鱼肌）。保持45秒，换边。',
        tip: '感受拉伸位置下移至跟腱上方，这是比目鱼肌',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c11-m4',
        name: '短足练习 SFE · 足弓激活',
        duration: 30,
        sets: 3,
        reps: '10次 / 保持10秒',
        desc: '坐或站立，脚掌放松放于地面。尝试将脚趾球（前掌）向脚跟方向靠拢（缩短足部），感受足弓被主动拱起——不是抓地或弯脚趾，而是足底内在肌收缩。保持10秒。',
        tip: '趾头不要弯曲，脚跟不要离地；这是细微的内在肌控制',
        icon: 'self_improvement',
        phase: 'activate',
      },
      {
        id: 'c11-m5',
        name: '毛巾抓取 · 趾屈肌激活',
        duration: 30,
        sets: 3,
        reps: '15次 / 足',
        desc: '赤脚站于毛巾或薄布上，用脚趾将毛巾向脚心方向抓起，保持1秒后放开。3组15次，激活足底趾屈肌群。',
        tip: '动作来自脚趾，不是整个脚；感受足底肌肉的参与',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c11-m6',
        name: '胫后肌 · 离心提踵',
        duration: 30,
        sets: 3,
        reps: '10次 / 侧 / 下落3秒',
        desc: '单腿站立于台阶边，用双腿一起踮起脚跟，然后单腿控制下落（3秒离心），感受内侧足弓和胫骨后肌的控制。10次后换边。',
        tip: '下落阶段越慢越有效；感受脚踝内侧肌肉的控制力',
        icon: 'fitness_center',
        phase: 'activate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C12  松而不塌 · 全身  (full, 中级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c12',
    name: '松而不塌 · 全身',
    desc: '全身秩序 · 松弛与力量共存',
    category: 'full',
    duration: 30,
    level: '中级',
    icon: 'fitness_center',
    bg: '1',
    evidence: 'A',
    scenes: ['home','gym'],
    targetMuscles: {
      activate: ['深颈屈肌', '中下斜方肌', '腹横肌', '臀大肌', '臀中肌', '足底内在肌'],
      release: ['上斜方肌', '胸肌', '髂腰肌'],
    },
    moves: [
      {
        id: 'c12-m1',
        name: '动态热身 · 全身律动',
        duration: 300,
        sets: 1,
        reps: '5分钟',
        desc: '包含：颈部缓慢侧弯旋转（各5次）、肩绕环（10次）、胸椎旋转（10次/侧）、髋绕环（10次/侧）、踝绕环（10次/侧）。节奏缓慢，唤醒全身关节。',
        tip: '热身是正式训练的基础，不要跳过；感受每个关节的流动',
        icon: 'directions_run',
        phase: 'release',
      },
      {
        id: 'c12-m2',
        name: '颈线内收 + 肩背YTW · 组合',
        duration: 30,
        sets: 2,
        reps: '各动作 10次',
        desc: '仰卧做颈线内收10次（每次保持5秒），随后翻身俯卧做YTW各10次（Y/T/W各10次）。两个动作连续完成为一组。',
        tip: '颈线内收和YTW是颈背姿态的核心组合，感受上下连贯',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c12-m3',
        name: '臀桥 + 死虫 · 超级组',
        duration: 40,
        sets: 3,
        reps: '各10次',
        desc: '先做臀桥10次（每次顶端2秒），不休息立即翻身做死虫8次/侧。两个动作连续完成为一组，激活臀部与深层核心。',
        tip: '超级组无需组间休息，感受臀部激活后核心的跟进',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c12-m4',
        name: '蚌式 + 鸟狗 · 稳定组合',
        duration: 35,
        sets: 3,
        reps: '各10次 / 侧',
        desc: '侧卧做蚌式10次/侧（弹力带可选），随后四足跪姿做鸟狗10次/侧（保持5秒）。强化臀中肌与腰背稳定的协同。',
        tip: '蚌式结束换边时检查骨盆是否还在中立位',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c12-m5',
        name: '深蹲 + 弓步 · 复合',
        duration: 40,
        sets: 3,
        reps: '各10次',
        desc: '先做深蹲10次（重心均匀，脊柱直立），随后做交替弓步10次（5次/侧）。感受下肢力量与全身稳定的整合。',
        tip: '两个动作都要保持膝盖不内扣、脊柱中立',
        icon: 'fitness_center',
        phase: 'integrate',
      },
      {
        id: 'c12-m6',
        name: '短足 + 单腿平衡 · 整合',
        duration: 30,
        sets: 3,
        reps: '30秒 / 侧',
        desc: '单腿站立时，同时保持短足练习（足弓主动拱起），感受从地面到脊柱的整体体态秩序。这是全身整合的终极挑战。',
        tip: '从足弓到膝盖、骨盆、脊柱的整体对齐——感受全身的秩序',
        icon: 'accessibility_new',
        phase: 'integrate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C13  产后 · 核心归位  (postpartum, 初级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c13',
    name: '产后 · 核心归位',
    desc: '温柔唤醒 · 腹部重新归位',
    category: 'postpartum',
    duration: 18,
    level: '初级',
    icon: 'spa',
    bg: '3',
    evidence: 'A',
    scenes: ['home'],
    targetMuscles: {
      activate: ['腹横肌', '盆底肌', '多裂肌'],
      release: ['腰方肌', '髋屈肌'],
    },
    moves: [
      {
        id: 'c13-m1',
        name: '横膈膜 · 呼吸唤醒',
        duration: 180,
        sets: 1,
        reps: '3分钟',
        desc: '仰卧屈膝，双手放于下腹两侧。吸气时让腹部、侧腰、后腰向四周轻轻扩张（360°呼吸），呼气时感受腹部自然回落、轻轻向内收拢。这是产后核心重建的第一步。',
        tip: '不要刻意鼓肚子或吸肚子，让呼吸自然带动',
        icon: 'spa',
        phase: 'release',
      },
      {
        id: 'c13-m2',
        name: '盆底 · 轻柔唤醒',
        duration: 120,
        sets: 3,
        reps: '10次 / 保持5秒',
        desc: '仰卧或侧卧，呼气时轻轻上提盆底（像轻轻憋住气流的感觉），保持5秒，吸气时完全放松。收紧与放松同样重要。',
        tip: '臀部和大腿保持放松，只用盆底深层发力；强度约30%即可',
        icon: 'spa',
        phase: 'activate',
      },
      {
        id: 'c13-m3',
        name: '腹横肌 · 贴合激活',
        duration: 120,
        sets: 3,
        reps: '10次 / 保持10秒',
        desc: '仰卧屈膝，呼气时将肚脐轻轻向脊柱方向贴近（约30%力度），同时配合盆底轻提，保持10秒自然呼吸后放松。',
        tip: '腹部中线如有明显鼓起或塌陷，减小幅度；这是腹直肌分离改善的核心动作',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c13-m4',
        name: '脚跟滑动 · 核心稳定',
        duration: 120,
        sets: 3,
        reps: '8次 / 侧',
        desc: '仰卧屈膝，保持腹横肌轻收，一侧脚跟沿地面缓慢向远处滑出伸直，再缓慢收回。全程腰部贴地、骨盆不晃动。',
        tip: '腰部一旦离地或腹部中线鼓起，缩小滑动幅度',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c13-m5',
        name: '臀桥 · 温和版',
        duration: 120,
        sets: 3,
        reps: '12次 / 保持2秒',
        desc: '仰卧屈膝，呼气时由臀部发力缓慢抬起骨盆，顶端保持2秒，吸气缓慢落回。唤醒臀部，分担腰部压力。',
        tip: '抬起高度以腰部无压力为准，不追求高度',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c13-m6',
        name: '侧卧 · 整体归位',
        duration: 90,
        sets: 2,
        reps: '45秒 / 侧',
        desc: '侧卧，双膝弯曲叠放，配合360°呼吸，呼气时轻收腹部与盆底，感受躯干像一个完整的圆筒被温柔地包裹归位。',
        tip: '这个姿势对产后腰部最友好，可作为每天的收尾放松',
        icon: 'spa',
        phase: 'integrate',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // C14  产后 · 骨盆安放  (postpartum, 初级)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'c14',
    name: '产后 · 骨盆安放',
    desc: '骨盆稳稳安放 · 身体重新立住',
    category: 'postpartum',
    duration: 20,
    level: '初级',
    icon: 'spa',
    bg: '6',
    evidence: 'A',
    scenes: ['home'],
    targetMuscles: {
      activate: ['臀中肌', '盆底肌', '腹横肌'],
      release: ['髋屈肌', '梨状肌', '腰方肌'],
    },
    moves: [
      {
        id: 'c14-m1',
        name: '骨盆 · 时钟律动',
        duration: 120,
        sets: 2,
        reps: '每个方向 8 次',
        desc: '仰卧屈膝，想象骨盆是一个时钟，缓慢做前倾（12点）、后倾（6点）、左右侧倾（3点9点）的小幅律动，重新找回骨盆的活动感知。',
        tip: '动作越小越好，专注感受而不是幅度',
        icon: 'rotate_right',
        phase: 'release',
      },
      {
        id: 'c14-m2',
        name: '梨状肌 · 4字舒展',
        duration: 90,
        sets: 2,
        reps: '45秒 / 侧',
        desc: '仰卧屈膝，一侧脚踝搭在对侧膝盖上呈4字，双手抱住下方大腿轻轻拉向胸口，感受臀部深层的舒展。',
        tip: '保持呼吸，骨盆贴地不要翘起',
        icon: 'self_improvement',
        phase: 'stretch',
      },
      {
        id: 'c14-m3',
        name: '髋前 · 半跪舒展',
        duration: 120,
        sets: 2,
        reps: '60秒 / 侧',
        desc: '半跪姿，骨盆轻轻后倾，身体直立前移，感受后腿髋前方的温和拉伸。孕期被缩短的髋前侧需要慢慢打开。',
        tip: '如膝盖不适可垫毛巾；幅度以舒适为准',
        icon: 'accessibility_new',
        phase: 'stretch',
      },
      {
        id: 'c14-m4',
        name: '蚌式 · 臀中肌唤醒',
        duration: 120,
        sets: 3,
        reps: '12次 / 侧',
        desc: '侧卧屈膝，脚跟并拢，呼气时上方膝盖缓慢打开，同时轻收盆底与腹部，顶端停留1秒后落回。唤醒孕产后沉睡的臀中肌。',
        tip: '骨盆保持稳定向前，不要随膝盖向后翻',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c14-m5',
        name: '鸟狗 · 温和版',
        duration: 120,
        sets: 3,
        reps: '8次 / 侧',
        desc: '四足跪姿，先只伸腿（手不动），熟练后再加对侧手臂。保持骨盆水平、腹部轻收，缓慢伸出与收回。',
        tip: '想象骨盆上放一杯水，全程不洒出来',
        icon: 'fitness_center',
        phase: 'activate',
      },
      {
        id: 'c14-m6',
        name: '靠墙 · 体态整合',
        duration: 120,
        sets: 2,
        reps: '60秒',
        desc: '靠墙站立，从足底到头顶逐一对齐：足弓轻拱、膝盖微弯、骨盆中立、腹部轻收、肩膀下沉、颈线向上。带着这份秩序感走入日常。',
        tip: '每天抱娃前后都可以做一次，让身体记住归位的感觉',
        icon: 'accessibility_new',
        phase: 'integrate',
      },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// PROGRAMS
// ─────────────────────────────────────────────────────────────────────────────

const programs = [
  // ───────────────────────────────────────────────────────────
  // P1  七日 · 焕新  (7天, 每天, 初级)
  // ───────────────────────────────────────────────────────────
  {
    id: 'p1',
    name: '七日 · 焕新',
    desc: '每天15分钟，重建身体的秩序',
    duration: 7,
    sessionsPerWeek: 7,
    level: '初级',
    icon: 'auto_awesome',
    color: '#c08a7d',
    scenes: ['home','office'],
    weeks: [
      {
        week: 1,
        days: [
          { day: 1, label: '第一天', courseId: 'c1', focus: '颈线唤醒' },
          { day: 2, label: '第二天', courseId: 'c3', focus: '肩背舒展' },
          { day: 3, label: '第三天', courseId: 'c5', focus: '骨盆归位' },
          { day: 4, label: '第四天', courseId: 'c7', focus: '腰背安放' },
          { day: 5, label: '第五天', courseId: 'c9', focus: '膝稳养成' },
          { day: 6, label: '第六天', courseId: 'c11', focus: '足弓生长' },
          { day: 7, label: '第七天', courseId: 'c12', focus: '全身整合' },
        ],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────
  // P2  八周 · 立  (8周, 3次/周, 中级)
  // ───────────────────────────────────────────────────────────
  {
    id: 'p2',
    name: '八周 · 立',
    desc: '循序渐进，八周重建身体的立体秩序',
    duration: 56,
    sessionsPerWeek: 3,
    level: '中级',
    icon: 'trending_up',
    color: '#7d9fc0',
    scenes: ['home','gym'],
    weeks: [
      // Week 1 — 基础激活
      {
        week: 1,
        days: [
          { day: 1, label: '第一天', courseId: 'c1', focus: '颈线基础激活' },
          { day: 3, label: '第三天', courseId: 'c3', focus: '肩背基础舒展' },
          { day: 5, label: '第五天', courseId: 'c5', focus: '骨盆基础归位' },
        ],
      },
      // Week 2 — 基础巩固
      {
        week: 2,
        days: [
          { day: 1, label: '第一天', courseId: 'c1', focus: '颈线巩固' },
          { day: 3, label: '第三天', courseId: 'c3', focus: '肩背巩固' },
          { day: 5, label: '第五天', courseId: 'c5', focus: '骨盆巩固' },
        ],
      },
      // Week 3 — 难度递进
      {
        week: 3,
        days: [
          { day: 1, label: '第一天', courseId: 'c2', focus: '颈背深层唤醒' },
          { day: 3, label: '第三天', courseId: 'c4', focus: '肩背深层打开' },
          { day: 5, label: '第五天', courseId: 'c6', focus: '核心进阶' },
        ],
      },
      // Week 4 — 难度递进巩固
      {
        week: 4,
        days: [
          { day: 1, label: '第一天', courseId: 'c2', focus: '颈背唤醒巩固' },
          { day: 3, label: '第三天', courseId: 'c4', focus: '肩背打开巩固' },
          { day: 5, label: '第五天', courseId: 'c6', focus: '核心巩固' },
        ],
      },
      // Week 5 — 功能强化
      {
        week: 5,
        days: [
          { day: 1, label: '第一天', courseId: 'c2', focus: '颈背功能强化' },
          { day: 3, label: '第三天', courseId: 'c8', focus: '腰背深层强化' },
          { day: 5, label: '第五天', courseId: 'c10', focus: '膝稳进阶强化' },
        ],
      },
      // Week 6 — 功能强化巩固
      {
        week: 6,
        days: [
          { day: 1, label: '第一天', courseId: 'c2', focus: '颈背强化巩固' },
          { day: 3, label: '第三天', courseId: 'c8', focus: '腰背强化巩固' },
          { day: 5, label: '第五天', courseId: 'c10', focus: '膝稳强化巩固' },
        ],
      },
      // Week 7 — 全身整合
      {
        week: 7,
        days: [
          { day: 1, label: '第一天', courseId: 'c12', focus: '全身整合' },
          { day: 3, label: '第三天', courseId: 'c12', focus: '全身整合强化' },
          { day: 5, label: '第五天', courseId: 'c12', focus: '全身整合巩固' },
        ],
      },
      // Week 8 — 全身整合收尾
      {
        week: 8,
        days: [
          { day: 1, label: '第一天', courseId: 'c12', focus: '全身整合进阶' },
          { day: 3, label: '第三天', courseId: 'c12', focus: '综合体态整合' },
          { day: 5, label: '第五天', courseId: 'c12', focus: '八周成果整合' },
        ],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────
  // P3  十二周 · 归位  (12周, 3-4次/周, 进阶)
  // ───────────────────────────────────────────────────────────
  {
    id: 'p3',
    name: '十二周 · 归位',
    desc: '十二周系统重塑，让身体回到它本该有的秩序',
    duration: 84,
    sessionsPerWeek: 4,
    level: '进阶',
    icon: 'workspace_premium',
    color: '#8d7dc0',
    scenes: ['home','gym'],
    weeks: [
      // ── Phase 1: 基础期 W1-4 ────────────────────────────────
      {
        week: 1,
        phase: '基础期',
        days: [
          { day: 1, label: '第一天', courseId: 'c1', focus: '颈线基础' },
          { day: 2, label: '第二天', courseId: 'c3', focus: '肩背舒展' },
          { day: 4, label: '第四天', courseId: 'c5', focus: '骨盆归位' },
          { day: 6, label: '第六天', courseId: 'c7', focus: '腰背安放' },
        ],
      },
      {
        week: 2,
        phase: '基础期',
        days: [
          { day: 1, label: '第一天', courseId: 'c9', focus: '膝稳基础' },
          { day: 2, label: '第二天', courseId: 'c11', focus: '足弓生长' },
          { day: 4, label: '第四天', courseId: 'c1', focus: '颈线巩固' },
          { day: 6, label: '第六天', courseId: 'c5', focus: '骨盆巩固' },
        ],
      },
      {
        week: 3,
        phase: '基础期',
        days: [
          { day: 1, label: '第一天', courseId: 'c3', focus: '肩背巩固' },
          { day: 2, label: '第二天', courseId: 'c7', focus: '腰背巩固' },
          { day: 4, label: '第四天', courseId: 'c9', focus: '膝稳巩固' },
          { day: 6, label: '第六天', courseId: 'c11', focus: '足弓巩固' },
        ],
      },
      {
        week: 4,
        phase: '基础期',
        days: [
          { day: 1, label: '第一天', courseId: 'c1', focus: '颈线深化' },
          { day: 2, label: '第二天', courseId: 'c3', focus: '肩背深化' },
          { day: 4, label: '第四天', courseId: 'c5', focus: '骨盆深化' },
          { day: 6, label: '第六天', courseId: 'c7', focus: '腰背深化' },
        ],
      },
      // ── Phase 2: 强化期 W5-8 ────────────────────────────────
      {
        week: 5,
        phase: '强化期',
        days: [
          { day: 1, label: '第一天', courseId: 'c2', focus: '颈背强化' },
          { day: 2, label: '第二天', courseId: 'c4', focus: '肩背强化' },
          { day: 4, label: '第四天', courseId: 'c6', focus: '核心强化' },
          { day: 6, label: '第六天', courseId: 'c8', focus: '腰背强化' },
        ],
      },
      {
        week: 6,
        phase: '强化期',
        days: [
          { day: 1, label: '第一天', courseId: 'c10', focus: '膝稳强化' },
          { day: 2, label: '第二天', courseId: 'c2', focus: '颈背强化进阶' },
          { day: 4, label: '第四天', courseId: 'c4', focus: '肩背强化进阶' },
          { day: 6, label: '第六天', courseId: 'c6', focus: '核心强化进阶' },
        ],
      },
      {
        week: 7,
        phase: '强化期',
        days: [
          { day: 1, label: '第一天', courseId: 'c8', focus: '腰背强化进阶' },
          { day: 2, label: '第二天', courseId: 'c10', focus: '膝稳强化进阶' },
          { day: 4, label: '第四天', courseId: 'c2', focus: '颈背功能强化' },
          { day: 6, label: '第六天', courseId: 'c4', focus: '肩背功能强化' },
        ],
      },
      {
        week: 8,
        phase: '强化期',
        days: [
          { day: 1, label: '第一天', courseId: 'c6', focus: '核心功能强化' },
          { day: 2, label: '第二天', courseId: 'c8', focus: '腰背功能强化' },
          { day: 4, label: '第四天', courseId: 'c10', focus: '膝稳功能强化' },
          { day: 6, label: '第六天', courseId: 'c12', focus: '全身预整合' },
        ],
      },
      // ── Phase 3: 整合期 W9-12 ───────────────────────────────
      {
        week: 9,
        phase: '整合期',
        days: [
          { day: 1, label: '第一天', courseId: 'c12', focus: '全身整合一' },
          { day: 2, label: '第二天', courseId: 'c2', focus: '颈背专项强化' },
          { day: 4, label: '第四天', courseId: 'c12', focus: '全身整合二' },
          { day: 6, label: '第六天', courseId: 'c8', focus: '腰背专项强化' },
        ],
      },
      {
        week: 10,
        phase: '整合期',
        days: [
          { day: 1, label: '第一天', courseId: 'c12', focus: '全身整合三' },
          { day: 2, label: '第二天', courseId: 'c4', focus: '肩背专项强化' },
          { day: 4, label: '第四天', courseId: 'c12', focus: '全身整合四' },
          { day: 6, label: '第六天', courseId: 'c10', focus: '膝稳专项强化' },
        ],
      },
      {
        week: 11,
        phase: '整合期',
        days: [
          { day: 1, label: '第一天', courseId: 'c12', focus: '全身整合强化一' },
          { day: 2, label: '第二天', courseId: 'c6', focus: '核心专项强化' },
          { day: 4, label: '第四天', courseId: 'c12', focus: '全身整合强化二' },
          { day: 6, label: '第六天', courseId: 'c11', focus: '足弓专项强化' },
        ],
      },
      {
        week: 12,
        phase: '整合期',
        days: [
          { day: 1, label: '第一天', courseId: 'c12', focus: '十二周收尾整合一' },
          { day: 2, label: '第二天', courseId: 'c12', focus: '十二周收尾整合二' },
          { day: 4, label: '第四天', courseId: 'c12', focus: '十二周收尾整合三' },
          { day: 6, label: '第六天', courseId: 'c12', focus: '十二周成果整合' },
        ],
      },
    ],
  },
];

module.exports = { courses, programs };
